# Generated by Django 4.0.6 on 2022-08-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_user_password_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
