# Generated by Django 4.0.6 on 2022-08-02 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_user_active_user_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='timestamp',
        ),
    ]
